spring:
  application:
    name: dipol-cadastro-documento-service
  main:
    banner-mode: "OFF"
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        
logging:
  level:
    root: INFO
    org.keycloak: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.tool.hbm2ddl: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE